---
- name: Ensures pet folder config
  file: path=~/.config/pet/ state=directory 

- name: pet config
  copy:
    src: ~/env/private/pet/config_linux.toml 
    dest: ~/.config/pet/config.toml
    force: no

