---
- name: Ensures pet folder config
  file: path=~/.config/pet/ state=directory 

- name: check private exist
  local_action: stat path={{ dotFilesPrivatePath }}/pet/config_linux.toml
  register: file

- name: pet config
  when: file.stat.exists
  copy:
    src: "{{ dotFilesPrivatePath }}/pet/config_linux.toml"
    dest: ~/.config/pet/config.toml
    force: no

