---
- name: Adding user synct
  become: yes
  user:
    name: synct
    group: synct
    shell: /bin/bash
    append: yes

- name: Change synct home folder to 770
  become: yes
  file:
    path: /home/synct
    state: directory
    recurse: yes
    mode: '0770'

- name: check private exist
  local_action: stat path=/home/synct/env-private/
  register: file

- name: link env private
  when: file.stat.exists
  file:
    src: /home/synct/env-private/
    dest: "{{ dotFilesPath }}/private"
    state: link

