---

- name: Adding user
  become: yes
  user:
    name: "{{ user }}"
    group: users
    shell: "{{ user_shell | default('/bin/bash') }}"
    groups: "{{ user_groups | default('wheel,input,docker,synct,gdrive,audio,storage,video') }}"
    append: yes

