---

- name: Adding user
  become: yes
  user: 
    name: "{{ user }}"
    group: users
    shell: /bin/bash
    groups: wheel,input,docker,synct,gdrive,audio
    append: yes
    
- name: Create .ssh folder
  become: true
  file:
    path: /home/{{ user }}/.ssh
    state: directory
    owner: "{{ user }}"
    group: users
    mode: 0700

- name: Copy ssh config
  when: dotFilesPrivatePath is defined
  become: true
  copy:
    src: "{{ dotFilesPrivatePath }}/ssh/ssh-config"
    dest: /home/{{ user }}/.ssh/config
    force: no
    owner: "{{ user }}"
    group: users
    mode: '0644'
