---

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Adding user
  become: yes
  user: 
    name: "{{ user }}"
    group: users
    shell: /bin/bash
    groups: wheel,input,docker,synct,gdrive,audio
    append: yes
