---
- name: Ensure zsh installed
  become: yes
  pacman:
    name: zsh
    state: present

- name: Clone oh-my-zsh
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    clone: yes
    update: no

- name: Basic zshrc
  become: yes
  become_user: "{{ user }}"
  template:
    src: ../templates/zshrc-basic.j2
    dest: ~/.zshrc
    force: no

- name: zshrc sources dotFiles defaults
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.zshrc
    regexp: '^source {{ dotFilesPath }}/bash/defaults$'
    line: source {{ dotFilesPath }}/bash/defaults

- name: zshrc sources dotFiles defaults_linux
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.zshrc
    regexp: '^source {{ dotFilesPath }}/bash/defaults_linux$'
    line: source {{ dotFilesPath }}/bash/defaults_linux

- name: zshrc sources dotFiles bin/commands
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.zshrc
    regexp: '^source {{ dotFilesPath }}/bin/commands$'
    line: source {{ dotFilesPath }}/bin/commands

- name: zshrc zoxide init
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.zshrc
    regexp: '^eval "\$\(zoxide init zsh\)"$'
    line: eval "$(zoxide init zsh)"

- name: zshrc pet-select bindkey
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.zshrc
    regexp: "^bindkey '\\^y' pet-select$"
    line: bindkey '^y' pet-select

- name: zshenv LANG
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.zshenv
    regexp: '^export LANG=en_US\.UTF-8$'
    line: export LANG=en_US.UTF-8
    create: yes

- name: zshenv LC_ALL
  become: yes
  become_user: "{{ user }}"
  lineinfile:
    path: ~/.zshenv
    regexp: '^export LC_ALL=en_US\.UTF-8$'
    line: export LC_ALL=en_US.UTF-8
    create: yes
