---
- name: ideavimrc
  file:
    src: "{{ dotFilesPath }}/idea/ideavimrc"
    dest: ~/.ideavimrc
    state: link

- name: bashrc defaults
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/bash/defaults'
    line: source {{ dotFilesPath }}/bash/defaults

- name: bashrc defaults_macos
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/bash/defaults_macos$'
    line: source {{ dotFilesPath }}/bash/defaults_macos

- name: bashrc private commands
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/private/commands$'
    line: source {{ dotFilesPath }}/bash/private/commands

- name: bashrc bin commands
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/bin/commands$'
    line: source {{ dotFilesPath }}/bash/bin/commands

- name: ackrc
  file:
    src: "{{ dotFilesPath }}/ack/ackrc"
    dest: ~/.ackrc
    state: link

- name: gitconfig
  file:
    src: "{{ dotFilesPath }}/gitconfig/gitconfig"
    dest: ~/.gitconfig
    state: link

- name: gitignore
  file:
    src: "{{ dotFilesPath }}/gitconfig/gitignore"
    dest: ~/.gitignore_global
    state: link

- name: vimrc
  file:
    src: "{{ dotFilesPath }}/vim/vimrc"
    dest: ~/.vimrc
    state: link

- name: vim
  file:
    src: "{{ dotFilesPath }}/vim/"
    dest: ~/.vim
    state: link

#- name: inputrc
#  file:
#    src: "{{ dotFilesPath }}/bash/inputrc"
#    dest: ~/.inputrc
#    state: link

- name: tmux
  file:
    src: "{{ dotFilesPath }}/tmux/tmux.conf"
    dest: ~/.tmux.conf
    state: link