---
- name: ideavimrc
  file:
    src: "{{ dotFilesPath }}/idea/ideavimrc"
    dest: ~/.ideavimrc
    state: link

- name: bashrc defaults
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/bash/defaults$'
    line: source {{ dotFilesPath }}/bash/defaults

- name: bashrc defaults_macos
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/bash/defaults_macos$'
    line: source {{ dotFilesPath }}/bash/defaults_macos

- name: bashrc bin commands
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/bin/commands$'
    line: source {{ dotFilesPath }}/bin/commands

- name: ackrc
  file:
    src: "{{ dotFilesPath }}/ack/ackrc"
    dest: ~/.ackrc
    state: link

- name: gitconfig
  file:
    src: "{{ dotFilesPath }}/gitconfig/gitconfig"
    dest: ~/.gitconfig
    state: link

- name: gitignore
  file:
    src: "{{ dotFilesPath }}/gitconfig/gitignore"
    dest: ~/.gitignore_global
    state: link

- name: vimrc
  file:
    src: "{{ dotFilesPath }}/vim/vimrc"
    dest: ~/.vimrc
    state: link

- name: vim
  file:
    src: "{{ dotFilesPath }}/vim/"
    dest: ~/.vim
    state: link

- name: tmux
  file:
    src: "{{ dotFilesPath }}/tmux/tmux.conf"
    dest: ~/.tmux.conf

- name: tmux kube
  git:
    repo: 'https://github.com/jonmosco/kube-tmux.git'
    dest: ~/.tmux/kube-tmux
    update: no

- name: yabairc
  file:
    src: "{{ dotFilesPath }}/yabai/yabairc"
    dest: ~/.config/yabai/yabairc
    state: link

- name: skhdrc
  file:
    src: "{{ dotFilesPath }}/yabai/skhdrc"
    dest: ~/.config/skhd/skhdrc
    state: link

- name: alacritty
  file:
    src: "{{ dotFilesPath }}/alacritty/alacritty.yml"
    dest: ~/.config/alacritty/alacritty.yml
    state: link

#  cp /opt/homebrew/opt/sketchybar/share/sketchybar/examples/sketchybarrc ~/.config/sketchybar/sketchybarrc
#  mkdir ~/.config/sketchybar/plugins
#  cp -r /opt/homebrew/opt/sketchybar/share/sketchybar/examples/plugins/ ~/.config/sketchybar/plugins/
#  chmod +x ~/.config/sketchybar/plugins/*

- name: Ensures sketchybar plugins
  file: path=~/.config/sketchybar/plugins state=directory

- name: sketchybar
  file:
    src: "{{ dotFilesPath }}/yabai/sketchybarrc"
    dest: ~/.config/sketchybar/sketchybarrc
    state: link

- name: Copy sketchybar plugins
  ansible.builtin.copy:
    src: /opt/homebrew/opt/sketchybar/share/sketchybar/examples/plugins
    dest: ~/.config/sketchybar
    mode: '0711'
