set number
set relativenumber
set ignorecase
set smartcase

filetype indent plugin on

set autoindent
set expandtab
set tabstop=4
set shiftwidth=4

autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" next/prev tab
map <A-}> gt
map <A-{> gT

" scroll screen up/down one line without moving the cursor
map <C-j> <C-e>
map <C-k> <C-y>

" vim-plug
call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'      " sane defaults every vimrc should have
Plug 'tpope/vim-surround'      " cs"' / ds( / ysiw) etc.
Plug 'tpope/vim-commentary'    " gcc to comment/uncomment
Plug 'tpope/vim-repeat'        " lets . repeat the plugins above
Plug 'junegunn/vim-easy-align' " ga to align on =, |, etc.
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'        " :Files :Buffers :Rg on top of fzf

Plug 'morhetz/gruvbox'

call plug#end()

syntax enable
set termguicolors
set background=dark
colorscheme gruvbox

" easy-align: ga in visual mode, gaip etc. in normal mode
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" fzf: fuzzy find files/buffers for quick edits
nnoremap <C-p> :Files<CR>
nnoremap <C-b> :Buffers<CR>
