---
- name: ensure zprofile exists
  copy:
    content: ""
    dest: ~/.zprofile
    force: false

- name: bashrc defaults
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/bash/defaults$'
    line: source {{ dotFilesPath }}/bash/defaults

- name: bashrc defaults_linux
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/bash/defaults_linux$'
    line: source {{ dotFilesPath }}/bash/defaults_linux

- name: bashrc bin commands
  lineinfile:
    path: ~/.zprofile
    regexp: '^source {{ dotFilesPath }}/bin/commands$'
    line: source {{ dotFilesPath }}/bin/commands

- name: ackrc
  file:
    src: "{{ dotFilesPath }}/ack/ackrc"
    dest: ~/.ackrc
    state: link

- name: gitconfig
  file:
    src: "{{ dotFilesPath }}/gitconfig/gitconfig"
    dest: ~/.gitconfig
    state: link

- name: gitignore
  file:
    src: "{{ dotFilesPath }}/gitconfig/gitignore"
    dest: ~/.gitignore_global
    state: link

- name: tmux
  copy:
    src: "{{ dotFilesPath }}/tmux/tmux.conf"
    dest: ~/.tmux.conf
    force: no

