#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

#!/usr/bin/env sh

# bar settings
# yabai -m config top_padding 0

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   10

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add app='^System Settings$' manage=off
yabai -m rule --add app='^Calculator$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add app='^Docker Desktop$' manage=off
yabai -m rule --add app='^Activity Monitor$' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

# Some Goland settings, in case you are using it. float Goland Preference panes
#yabai -m rule --add app='IntelliJ IDEA' title='^$' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Project Structure' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Preferences' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Edit configuration' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Data Sources and Drivers' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Keymap' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Keyboard Shortcut' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Copy' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Rename' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Add File to Git' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Delete' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Implement Members' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Create Test' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Run/Debug Configurations' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Plugins Updates' manage=off
yabai -m rule --add app='IntelliJ IDEA' title='Move' manage=off

yabai -m rule --add title='^scratch$' manage=off
yabai -m rule --add app='^CopyQ$' manage=off
yabai -m rule --add app='^YouTube Music$' manage=off
yabai -m rule --add app='Microsoft Teams' title='^Call with' manage=off
yabai -m rule --add app='^KeePassXC$' manage=off
yabai -m rule --add app='^Weather$' manage=off
yabai -m rule --add app='^Disk Utility$' manage=off
yabai -m rule --add app='^ViewerKt$' manage=off

#yabai -m rule --add app='^Unity$' manage=off

echo "yabai configuration loaded.."

