---
- hosts: localhost
  tasks:
   - include_tasks: tools/users.yml
     when: user is defined

   - include_tasks: tools/dotFiles.yml
     when: dotFilesPath is defined

   # - include_tasks: tools/ssh.yml
   #   when: ssh is defined
