---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - alacritty
      - copyq
      - docker
      - firefox
      - jetbrains-toolbox
      - keepassxc
      - microsoft-teams
      - slack
      - visual-studio-code
    brew_packages:
      - ack
      - bat
      - azure-cli
      - calcurse
      - cmake
      - docker-buildx
      - fzf
      - go
      - git
      - git-crypt
      - git-lfs
      - gradle
      - helm
      - jenv
      - jq
      - knqyf263/pet/pet
      - kubernetes-cli
      - lazygit
      - maven
      - ncdu
      - node
      - openjdk@11
      - openjdk@17
      - peco
      - sfml
      - ranger
      - tig
      - tmux
      - wget
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

#    - name: Installing Homebrew
#      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#      when:
#        - not homebrew_check.stat.exists
#        - install_homebrew_if_missing

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
    # - name: Installing Python Modules
    #   pip:
    #     name: "{{ item }}"
    #     state: present
    #   with_items: '{{ python_modules }}'
