---
- name: Install MacOS Packages
  hosts: localhost
  become: false
  vars:
    brew_cask_packages:
      - firefox
    brew_packages:
      - git
      - git-lfs
      - tmux
      - wget
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false
