---
- aur:
    skip_installed: true
    name:
      - intellij-idea-ultimate-edition
      - google-chrome
      - dropbox
      - skypeforlinux-stable-bin
      - slack-desktop
      - libinput-gestures
      - gotop
      - system-san-francisco-font-git
      - ttf-symbola 
