---
- name: ideavimrc
  file:
    src: ~/env/idea/ideavimrc
    dest: ~/.ideavimrc
    state: link

- name: compose key
  become: true
  copy:
    src: ~/env/x/compose-key.sh
    dest: /etc/X11/xinit/xinitrc.d/60-compose-key.sh
    owner: root
    group: root
    mode: '0755'

- name: i3 folder
  file:
    path: ~/.i3
    state: directory
    mode: '0755'

- name: i3 config
  file:
    src: ~/env/i3/config
    dest: ~/.i3/config
    state: link

- name: i3status folder
  file:
    path: ~/.config/i3status
    state: directory
    mode: '0755'

- name: i3status
  copy:
    src: ~/env/i3/i3status-config-xps.template
    dest: ~/.config/i3status/config

- name: Ensures systemd user dir exists
  file: path=~/.config/systemd/user/ state=directory 

- name: copy fix temp service
  copy:
    src: ~/env/i3/i3-temp.service
    dest: ~/.config/systemd/user/i3-temp.service
    force: no

- name: enable fix temp service
  systemd:
    name: i3-temp
    enabled: yes
    masked: no
    scope: user
