---
- name: ideavimrc
  file:
    src: ~/env/idea/ideavimrc
    dest: ~/.ideavimrc
    state: link

- name: compose key
  become: true
  copy:
    src: ~/env/x/compose-key.sh
    dest: /etc/X11/xinit/xinitrc.d/60-compose-key.sh
    owner: root
    group: root
    mode: '0755'

- name: i3 folder
  file:
    path: ~/.i3
    state: directory
    mode: '0755'

- name: i3 config
  file:
    src: ~/env/i3/config
    dest: ~/.i3/config
    state: link

- name: i3status folder
  file:
    path: ~/.config/i3status
    state: directory
    mode: '0755'

- name: i3status
  copy:
    src: ~/env/i3/i3status-config-xps.template
    dest: ~/.config/i3status/config

- name: Ensures systemd user dir exists
  file: path=~/.config/systemd/user/ state=directory 

- name: copy fix temp service
  copy:
    src: ~/env/i3/i3-temp.service
    dest: ~/.config/systemd/user/i3-temp.service
    force: no

- name: enable fix temp service
  systemd:
    name: i3-temp
    enabled: yes
    masked: no
    scope: user

- name: link libinput gestures
  file:
    src: ~/env/i3/libinput-gestures.conf
    dest: ~/.config/libinput-gestures.conf
    state: link

- name: copy intellij file inode
  become: true
  copy:
    src: /home/fabio/env/idea/98-idea.conf
    dest: /etc/sysctl.d/98-idea.conf
    force: no
    owner: root
    group: root
    mode: '0755'

- name: apple magic keyboard
  become: true
  copy:
    src: ~/env/keyboard/hid_apple.conf 
    dest: /etc/modprobe.d/hid_apple.conf
    force: no
    owner: root
    group: root
    mode: '0755'

- name: libinput trackpad
  become: true
  copy:
    src:  ~/env/x/90-libinput.conf
    dest:  /etc/X11/xorg.conf.d/
    force: no
    owner: root
    group: root
    mode: '0755'

- name: Ensures termite dir exists
  file: path=~/.config/termite/ state=directory 

- name: termite config
  file:
    src: ~/env/termite/config
    dest: ~/.config/termite/config
    state: link

