---
- hosts: localhost
  tasks:
   - include: tools/users.yml
     when: user is defined

   - include: tools/dotFiles.yml
     when: dotFiles is defined

   - include: tools/ssh.yml
     when: ssh is defined
