---
- hosts: localhost
  tasks:
   - include_tasks: tools/users.yml
     when: user is defined

   - include_tasks: tools/dotFiles.yml
     when: dotFiles is defined

   - include_tasks: tools/zsh.yml
     when: zsh is defined

   - block:
       - include_tasks: base/user-config.yml
     when: dotFiles is defined
     become: yes
     become_user: "{{ user }}"
