---
- name: Ensure group exists
  become: yes
  group:
    name: docker
    state: present

- name: Ensure group exists
  become: yes
  group:
    name: input
    state: present

- name: Ensure group exists
  become: yes
  group:
    name: synct
    state: present


- name: Adding user
  become: yes
  user: 
    name: "{{ user }}"
    group: users
    shell: /bin/bash
    groups: input,docker,synct
    append: yes

- name: Ensures pet folder config
  file: path=~/.config/pet/ state=directory 

- name: pet config
  copy:
    src: ~/env/private/pet/config_linux.toml 
    dest: ~/.config/pet/config.toml
    force: no

