---
- name: Install base packages
  become: yes
  pacman:
    name: 
      - base-devel
      - git
      - openssh
      - rsync
      - vim
      - go
      - jdk11-openjdk
      - jdk8-openjdk
      - maven
      - ack
      - tig
      - yq
      - jq
      - wget
      - unrar
      - unzip
      - bash-completion
    state: present
