---
- name: Install base packages
  become: yes
  pacman:
    name: 
      - i3-wm
      - dmenu
      - termite
      - firefox
      - pavucontrol
      - openjdk11-src
      - keepass
      - copyq
      - xdotool 
      - wmctrl
      - syncthing
      - ttf-dejavu
    state: present
