---
- hosts: localhost
  tasks:
   - include_tasks: base/sys-packages.yml
     when: run_pacman is defined

   - include_tasks: tools/groups.yml
   - include_tasks: base/sys-config.yml
   - include_tasks: tools/basic-services.yml

   - include_tasks: tools/users.yml
     when: user is defined

   - include_tasks: tools/dotFiles.yml
     when: dotFiles is defined

   - include_tasks: tools/ssh.yml
     when: ssh is defined
