---
- hosts: localhost
  tasks:
   - include_tasks: base/sys-packages.yml
     when: run_pacman is defined

   - include_tasks: tools/yay.yml
     when: run_aur is defined

   - include_tasks: base/sys-packages-aur.yml
     when: run_aur is defined

   - include_tasks: base/user-packages.yml
     when: run_pacman is defined

   - include_tasks: base/user-packages-aur.yml
     when: run_aur is defined

   - include_tasks: tools/groups.yml
   - include_tasks: base/sys-config.yml

   - include_tasks: tools/basic-services-ui.yml
     when: ui is defined

   - include_tasks: tools/gdrive.yml
   - include_tasks: tools/syncthing.yml

   - include_tasks: tools/syncthing-service.yml
     when: syncthingservice is defined

   - include_tasks: base/user-config.yml
   - include_tasks: tools/pet.yml
   - include_tasks: tools/jenv.yml

   - include_tasks: tools/ssh.yml
     when: ssh is defined
