#!/bin/sh

if [[ -n $ZSH_VERSION ]]; then
  function pet-select() {
    BUFFER=$(pet search --query "$LBUFFER")
    CURSOR=$#BUFFER
    zle redisplay
  }
  zle -N pet-select
  bindkey '^y' pet-select
fi
stty -ixon

