#!/bin/sh

export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

function pet-select() {
  BUFFER=$(pet search --query "$LBUFFER")
  CURSOR=$#BUFFER
  zle redisplay
}
zle -N pet-select
stty -ixon

# needs to be copied to the last line of .zshrc
bindkey '^y' pet-select
