#!/bin/sh

#export DOCKER_HOST=tcp://192.168.59.103:2376
export DOCKER_CERT_PATH=/Users/fabio/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1

export PATH=~/bin:$PATH
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export M3_HOME=/usr/local/Cellar/maven/3.2.5/

