#!/bin/sh

export TERM=xterm-256color

export EDITOR=`which vim`

export sconsify=~/go/src/github.com/fabiofalci/sconsify/

export GOPATH=~/go
export PATH=$PATH:~/go/bin

export GROOVY_HOME=/opt/groovy
export PATH=$GROOVY_HOME/bin:$PATH

export GRADLE_HOME=/opt/gradle
export PATH=$GRADLE_HOME/bin:$PATH

export PATH=$PATH:~/env/bin

alias docker_rm_all='docker rm `docker ps --no-trunc -aq`'
alias docker_ip='docker inspect --format "{{ .NetworkSettings.IPAddress }}" $1'
alias vi='vim'
alias h='history | grep $1'
alias g=git
alias open=xdg-open
alias autossh_='autossh -M 0 -o "ServerAliveInterval 45" -o "ServerAliveCountMax 2"'
alias p='ps -ef | grep $1'
alias f='find | grep $1'
alias server='cat ~/.ssh/config | grep -A1 $1'
alias k9='kill -9 $1'
alias du1='du -h -d 1'
