#!/bin/sh

export TERM=xterm-256color

export EDITOR=`which vim`

export sconsify=~/go/src/github.com/fabiofalci/sconsify/

export GOPATH=~/go
export PATH=$PATH:~/go/bin

export PATH=$PATH:~/env/bin

export PATH=~/bin:$PATH

# basic just-in-time compilation of the code only
export MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
export FAST_MAVEN="--threads 1.5C"

alias docker_rm_all='docker rm `docker ps --no-trunc -aq`'
alias docker_ip='docker inspect --format "{{ .NetworkSettings.IPAddress }}" $1'
alias vi='vim'
alias h='history | grep $1'
alias g=git
__git_complete g _git
alias autossh_='autossh -M 0 -o "ServerAliveInterval 45" -o "ServerAliveCountMax 2"'
alias p='ps -ef | grep $1'
alias f='find | grep $1'
alias server='cat ~/.ssh/config | grep -A1 $1'
alias k9='kill -9 $1'
alias du1='du -h -d 1'
eval "$(thefuck --alias)"
alias prettyjson='python -m json.tool'
alias copy='xclip -selection clipboard'
