---
- name: ideavimrc
  file:
    src: ~/env/idea/ideavimrc
    dest: ~/.ideavimrc
    state: link

- name: i3 folder
  file:
    path: ~/.config/i3
    state: directory
    mode: '0755'

- name: i3 config
  file:
    src: ~/env/i3/config-user
    dest: ~/.config/i3/config
    state: link

- name: i3status folder
  file:
    path: ~/.config/i3status
    state: directory
    mode: '0755'

- name: i3status
  copy:
    src: ~/env/i3/i3status-config-user.template
    dest: ~/.config/i3status/config

- name: link libinput gestures
  file:
    src: ~/env/i3/libinput-gestures.conf
    dest: ~/.config/libinput-gestures.conf
    state: link
