---
- name: Install sys base packages
  become: yes
  pacman:
    name: 
      - base-devel
      - git
      - openssh
      - rsync
      - vim
      - go
      - jdk17-openjdk
      - jdk11-openjdk
      - jdk8-openjdk
      - maven
#      - gradle
      - ack
      - tig
      - jq
      - wget
      - unrar
      - unzip
      - bash-completion
      - man-db
      - man-pages
      - htop
      - ranger
      - mlocate
      - mitmproxy
      - tmux
      - bc
      - yq
      - ntp
      - lazygit
      - yt-dlp
      - pacman-contrib
      - helm
      - ncdu
      - sudo
    state: present
