---

- name: Ensure the locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: set as default locale
  command: localectl set-locale LANG=en_US.UTF-8 

- name: compose key
  become: true
  copy:
    src: ~/env/x/compose-key.sh
    dest: /etc/X11/xinit/xinitrc.d/60-compose-key.sh
    owner: root
    group: root
    mode: '0755'

- name: copy intellij file inode
  become: true
  copy:
    src: ~/env/idea/98-idea.conf
    dest: /etc/sysctl.d/98-idea.conf
    force: no
    owner: root
    group: root
    mode: '0755'

- name: apple magic keyboard
  become: true
  copy:
    src: ~/env/keyboard/hid_apple.conf 
    dest: /etc/modprobe.d/hid_apple.conf
    force: no
    owner: root
    group: root
    mode: '0755'

- name: libinput trackpad
  become: true
  copy:
    src:  ~/env/x/90-libinput.conf
    dest:  /etc/X11/xorg.conf.d/
    force: no
    owner: root
    group: root
    mode: '0755'
