---
- aur:
    state: present
    when: run_aur is defined
    name:
      - alacritty-themes
      - apple-fonts
      - cyberchef-web
      - drive-bin
      - gotop

- aur:
    state: present
    when: ui is defined
    name:
      - connman-gtk
      - dropbox
      - google-chrome
      - libinput-gestures
      - moka-icon-theme
      - notion-app
      - qomui
      - slack-desktop
      - teams
      - ttf-font-awesome
      - ttf-nerd-fonts-symbols
      - ttf-symbola
