---
- name: Install user base packages
  when: run_pacman is defined
  become: yes
  pacman:
    name:
      - bluez
      - bluez-utils
      - calcurse
      - docker
      - ffmpeg
      - git-crypt
      - github-cli
      - gnome-keyring
      - wireguard-tools
    state: present

- name: Install user ui packages
  when: ui is defined
  become: yes
  pacman:
    name:
      - alacritty
      - alsa-utils
      - arandr
      - arc-gtk-theme
      - autorandr
      - copyq
      - dmenu
      - dunst
      - firefox
      - i3-gaps
      - i3lock
      - i3status
      - keepass
      - keepass
#      - libsmbios
      - lightdm
      - lxappearance
      - mplayer
      - openjdk11-src
      - pavucontrol
      - picom
      - portaudio
      - pulseaudio
      - pulseaudio-alsa
#      - syncthing
      - thunar
      - ttf-dejavu
      - vlc
      - wmctrl
      - xclip
      - xdotool
    state: present
